name: .NET Core Build

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

    
jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      file_matrix: ${{ steps.list_files.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run App
        run: dotnet run --project ./src/DntSdkMirror/DntSdkMirror.csproj

      - name: List all files in sdks folder
        id: list_files
        run: |
          # پیدا کردن مسیر تمام فایل‌های exe
          files=$(find sdks -type f -name "*.exe" 2>/dev/null || echo "")
          if [ -z "$files" ]; then
            echo "matrix=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
          # تبدیل به آرایه JSON فشرده (بدون فاصله و خط جدید اضافی)
          json_array=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length>0))')
          echo "matrix=$json_array" >> $GITHUB_OUTPUT
    
  upload:
    needs: download
    runs-on: ubuntu-latest
    if: needs.download.outputs.file_matrix != '[]'
    strategy:
      matrix:
        file: ${{ fromJson(needs.download.outputs.file_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get artifact name from file path
        id: artifact_name
        run: |
          # استخراج فقط نام فایل بدون مسیر
          filename=$(basename "${{ matrix.file }}")
          echo "name=$filename" >> $GITHUB_OUTPUT

      - name: Upload single file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: ${{ matrix.file }}
          retention-days: 7
